Settings:
  max_history: 7  # 最多保留最近7天的文章
  load_images: true  # 是否加载图片
  filename_template: "RSS订阅_{date}.epub"  # 自定义文件名模板
  # 可用占位符:
  # {year} - 年份 (2025)
  # {month} - 月份 (07)
  # {day} - 日期 (04)
  # {hour} - 小时 (14)
  # {minute} - 分钟 (30)
  # {second} - 秒 (45)
  # {date} - 中文日期 (2025年7月4日)
  # {time} - 中文时间 (14时30分)
  # {datetime} - 中文日期时间 (2025年7月4日_14时30分)
  # 示例: "RSS精选_{date}.epub" → "RSS精选_2025年7月4日.epub"

Feeds:
  # 示例1: 使用CSS选择器提取内容
  - url: "https://sspai.com/feed"
    name: "少数派"
    title: "少数派精选"
    enabled: true
    resolve_link:
      enabled: true
      method: "selector"  # 优先使用选择器
      selectors:
        content: "article, .post-content, .article-content, main"  # 内容选择器
        remove: ".ads, .comments, .related-posts, script, style"  # 要移除的元素
      fallback: "readability"  # 选择器失败时使用readability

  # 示例2: 直接使用readability自动提取
  - url: "https://feeds.feedburner.com/ruanyifeng"
    name: "阮一峰"
    title: "阮一峰的网络日志"
    enabled: true
    resolve_link:
      enabled: true
      method: "readability"  # 直接使用readability

  # 示例3: 不解析原始链接，使用RSS摘要
  - url: "https://www.v2ex.com/index.xml"
    name: "V2EX"
    title: "V2EX热门"
    enabled: true
    # 没有resolve_link配置，使用默认RSS内容